baseurl = "http://graymalk.in/tinker-new"
languageCode = "en-gb"
title = "TinkerSoc Website"
theme = "TinkerSoc"

[menu]
    [[menu.main]]
    name = "TinkerSoc"
    pre = "<span><img src='/images/logo_trans.png' alt='logo'</img></span>"
    weight = 1
    identifier = "home"
    url = "/"
    [[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"
    [[menu.main]]
    name = "Resources"
    weight = 10
    identifier = "resources"
