name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4.1.0

    - name: Install Hugo
      run: go install github.com/gohugoio/hugo@latest

    - name: Install image-gen
      run: go install github.com/TinkerSoc/image-gen@latest

    - name: Build website
      run: make all

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: public/

  deploy:
    needs: build-and-upload
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
        
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Pages artifact
      id: deployment
      uses: actions/deploy-pages@v2
